import { ironHeaders } from './iron-sign.ts';

const API_BASE = 'https://ostvapp.cam/api';
const IMG_BASE = 'https://ostvapp.cam';

export async function fetchJson(path) {
  // X-Iron-* signature headers — generated by emulating the app's native signer.
  // Requests go directly to the API (server-side, no CORS proxy needed).
  const headers = ironHeaders(path);
  headers['User-Agent'] = 'okhttp/4.9.0';
  const res = await fetch(API_BASE + path, { headers, signal: AbortSignal.timeout(20000) });
  if (res.status === 403) return null; // invalid id -> API answers 403
  if (!res.ok) throw new Error('HTTP ' + res.status);
  const json = await res.json();
  if (json.status !== 'success' || !json.data) return null;
  return json.data;
}

export function absUrl(u) {
  if (!u) return '';
  if (u.startsWith('http')) return u;
  return IMG_BASE + u;
}

export function mapWatchLinks(list) {
  return (list || [])
    .map((l) => ({ name: l.server_name, url: l.url, quality: l.quality || '' }))
    .filter((l) => l.url);
}

export function mapDownloadLinks(list) {
  return (list || [])
    .map((l) => ({ name: l.server_name, url: l.url, quality: l.quality || '', size: l.file_size || '' }))
    .filter((l) => l.url);
}

export function mapChannelStreams(d) {
  return (d.streams || [])
    .map((s) => ({ name: s.server_name, url: s.stream_url, quality: s.quality || '' }))
    .filter((s) => s.url);
}

export function mapMovieDetails(d) {
  return {
    source_id: d.id,
    title: d.title_ar || d.title_en || '',
    title_en: d.title_en || '',
    story: d.story || '',
    poster_url: absUrl(d.poster),
    banner_url: absUrl(d.banner),
    trailer_url: d.trailer_url || '',
    year: Number(d.release_year) || 0,
    rating: Number(d.rating) || 0,
    runtime: Number(d.runtime) || 0,
    language: d.language || '',
    country: d.country_name || d.country || '',
    categories: (d.categories || []).map((c) => c.name_ar || c.name_en).filter(Boolean),
  };
}

export function mapSerieDetails(d) {
  return {
    source_id: d.id,
    title: d.title_ar || d.title_en || '',
    title_en: d.title_en || '',
    story: d.story || '',
    poster_url: absUrl(d.poster),
    trailer_url: d.trailer_url || '',
    year: Number(d.release_year) || 0,
    rating: Number(d.rating) || 0,
    episode_count: Number(d.episode_count) || 0,
    language: d.language || '',
    country: d.country || '',
    seasons: (d.seasons || []).map((s) => ({
      season_source_id: s.id,
      season_number: s.season_number,
      title: s.title || 'الموسم ' + s.season_number,
      poster_url: absUrl(s.poster),
    })),
  };
}

export function mapEpisodeDetails(d) {
  return {
    source_id: d.id,
    series_id: d.series_id,
    season_id: d.season_id,
    season_number: d.season_number,
    number: d.episode_number,
    title: d.title || 'الحلقة ' + d.episode_number,
    description: d.description || '',
    thumbnail_url: absUrl(d.thumbnail),
    air_date: d.air_date || '',
    duration: d.duration != null ? String(d.duration) : '',
  };
}

export function mapChannelDetails(d, groupName) {
  return {
    source_id: d.id,
    name: d.name,
    group_name: groupName || '',
    logo_url: absUrl(d.logo),
    country: d.country_name || d.country || '',
    category: d.category_label || d.category || '',
    description: d.description || d.frequency || '',
  };
}